version: '2'
services:
  nginx:
    image: nginx
    container_name: docker-nginx-vue
    restart: always
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./dist:/dist
      - ./dist:/usr/share/nginx/html:rw # 可选的参数是 :ro或者 :rw
      - ./dockerConfig/config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro # 挂载nginx配置文件
      - ./dockerConfig/config/nginx/conf.d:/etc/nginx/conf.d # 挂载 conf.d文件夹
      - ./dockerConfig/config/nginx/logs:/var/log/nginx  # 挂载日志
    restart: always